### ISSUE TITLE
Health List

### ISSUE THREAD

**Issue by Elforia** [Mytherin/Tibialyzer#302]
It is not working. May someone fix it? Please?

**Comment by WadeDro** [comment]
Having the same issue as me? I set in advanced options (health list) the char's I would like to keep and eye on being a ed this is super useful but I am not getting any luck with it after I click re-fresh and turn on huds still nothing, I have my own health and mana bar up on screen but nothing comes up when I try my healthlist huds :/

**Comment by Elforia** [comment]
Yes, man. I am facing the same issue as you. It is bothering me, because I saw that we are not the only ones who face that problem, but nobody appears to fix it. Looks like nobody know how to do it, or maybe just don't want to. Sadly.

**Comment by WadeDro** [comment]
Yeah unfortunately no one else has spoken up, or maybe isn't having the same issues as us, but its really getting to me :p so hopefully someone or Myth him self gets at this issue I feel it was something to do with a small client update but sadly I am not at all computer alliterate ha

**Comment by Galeonz** [comment]
I play on Tibia 11 and I have the same issue. The "Health List" HUD doesn't work at all.
I click the "Show HUD" button and nothing happens.

**Comment by WadeDro** [comment]
I received a notification email saying this probalen should be fixed just update it in the .exe launder aka tibialyzer and give er a go! I haven't been on since to check this my self thought I'd relay the message as well!

**Comment by Galeonz** [comment]
@WadeDro @Elforia 
> I received a notification email saying this problem should be fixed just update it in the .exe launcher aka tibialyzer and give er a go!

Well, I clicked "Update database" and "Download new Addresses" and the Health List HUD still doesn't work. Tell me if it works for you guys.

**Comment by Elforia** [comment]
@WadeDro @Galeonz
Nothing has changed and will not change. Someone needs ti fix it, as Mytherin said some time ago on Reddit. Maybe it never happen.

**Comment by WadeDro** [comment]
I haven't made it home to check my self with the program, but I will let you no soon as I get a chance
to test it!

**Comment by Ne0nyx** [comment]
I used a debugger and can confirm that the array that holds all the battlelist entries (player info like health) stays empty after every memory read cycle. The HealthList function is correct the problem is with reading the battlelist from the tibia client. Someone has to find a way to get the correct battlelist address and then the HealthList will work again.

**Comment by Ne0nyx** [comment]
I used a debugger to pinpoint the problem and the Health List is just fine but the players health cannot be read from the tibia client memory so unless someone implements a new memory read method for the new Tibia 11 client battle list the health list is unusable.

**Comment by WadeDro** [comment]
Has anyone got the HEALTH LIST working for there tibia 11 clients yet? and is anyones popup item value keep resetting?
